### ISSUE TITLE
The tiny thruster max upgrade description is wrong

### ISSUE THREAD

**Issue by Ultra-bob** [alex-s168/VS_tournament_continued#10]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20​

### Mod Loader

Forge

### Issue description

![image](https://github.com/alex-s168/VS_tournament_continued/assets/66791664/dc10c7ba-b4df-4983-b4af-885421e88ac4)

### Issue reproduction

N/A

### Logs

N/A

**Comment by alex-s168** [comment]
Fixed!
