### ISSUE TITLE
VST makes CCVS's Ship API disappear

### ISSUE THREAD

**Issue by xiewuzhiying** [alex-s168/VS_tournament_continued#11]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

VST makes CCVS's Ship API disappear.
Expectation: Both mods work fine.

### Issue reproduction

- Build mod files from the latest VST source code
- Install VST and CCVS at the same time
- Turning on the computer on the ship, the Ship API cannot be found
![2024-01-23_16 18 15](https://github.com/alex-s168/VS_tournament_continued/assets/92735961/379cf2a3-cd9e-4bba-92ba-6e27b0d661b1)
![2024-01-23_16 18 42](https://github.com/alex-s168/VS_tournament_continued/assets/92735961/818675cf-d5d3-4a18-8f94-116616a2fae9)

**Comment by alex-s168** [comment]
That's weird.
I will look into it

**Comment by alex-s168** [comment]
Can the Tournament API be found?

**Comment by xiewuzhiying** [comment]
(I realize now that I chose the wrong issue template, but it does not affect what I want to express)
The Tournament API can be found.
`vst_components` will only return an empty table.
`vst_chunks` I haven't confirmed if it works yet.

**Comment by alex-s168** [comment]
okay i have never tested `vst_components` so i can't confirm that that's what happens under normal circumstances
~~Wait we have issue templates?~~
Tech and me are trying to solve that problem. (we both do the same thing kinda and they overwrite each other)

**Comment by alex-s168** [comment]
I'm 99% sure that this will be fixed with #12 (already merged) and https://github.com/TechTastic/CC-VS/pull/1
