### ISSUE TITLE
vst_components.get_thrusters() pos value is off by 0.5

### ISSUE THREAD

**Issue by 19PHOBOSS98** [alex-s168/VS_tournament_continued#17]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

Hey Alex, I take it that the `pos` value is the vector between the thruster and the ship's center of mass but I think the coordinate values that `vst_component.getThrusters()` returns are off by 0.5

![image](https://github.com/alex-s168/VS_tournament_continued/assets/37253663/d5c88ac0-0676-4091-9a04-ef792560c065)

![image](https://github.com/alex-s168/VS_tournament_continued/assets/37253663/d8a3d22c-f4e7-446e-90e3-66dbbc35addc)

Thruster Shipyard Position:
(-28669949, -53, 12290060)
Thruster Shipyard Position CENTERED:
(-28669948.5, -52.5, 12290060.5)

Ship Center Of Mass in Shipyard:
(-28669948.5, -50.5, 12290060.5)

thruster's actual radius vector from center of mass:
-28669948.5 - -28669948.5 = 0
-52.5 - -50.5 = -2
12290060.5 - 12290060.5 = 0
(0, -2, 0)

`vst_component.getThrusters()[3] :`
![image](https://github.com/alex-s168/VS_tournament_continued/assets/37253663/a526b484-4ba3-4c59-98b6-b3b2ddcbd0db)

subtracting 0.5 from the value gives you the actual radius vector
x = 0.49999... - 0.5 = ~0
y = -1.5 - 0.5 = -2
z = 0.5 - 0.5 = 0

I also tried doing this for the rest of my thrusters and the results are consistent

### Issue reproduction

1. hit F3 and hover over an active thruster to get its shipyard coordinates
2. use CC:VS ShipAPI: `ship.getShipyardPosition()` to get center of mass position in shipyard coordinates
3. subtract center of mass from thruster position (thruster_pos - COM)
4. use `vst_component.getThrusters()` to view the `pos` value of the active thruster
5. compare returned value with calculated value

**Comment by alex-s168** [comment]
So I just need to `x - (0.5, 0.5, 0.5)` and it always works?
can you please verify

**Comment by 19PHOBOSS98** [comment]
> So I just need to `x - (0.5, 0.5, 0.5)` and it always works? can you please verify

slr, yeah, I think it's just off centered

**Comment by alex-s168** [comment]
fixed with
